version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2022-02-01 to 2023-01-01 by month" --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  generate_outputs:
    run: python:latest python analysis/check_outputs.py
    needs: [generate_study_population]
    outputs: 
      moderately_sensitive:
        measure_csv: output/inpu*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [generate_study_population]
    outputs: 
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv
