version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-01-01 to 2019-12-01 by month" --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input*.csv

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2021-12-01 by month" --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv
  
  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2022-01-01 to 2023-04-01 by month" --output-dir=output --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv
 
  generate_indication:
    run: python:latest python analysis/indication_variables.py
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3]
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv
  
  generate_medication:
    run: python:latest python analysis/medication_variables.py
    needs: [generate_indication]
    outputs:
      highly_sensitive:
        cohort: output/in*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
    needs: [generate_medication]
    outputs: 
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv

  generate_report:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/report*.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/report*.html
        plots: output/*.png